spring:
  application:
    name: hello-gemini
  ai:
    vertex:
      ai:
        gemini:
          project-id: <PROJECT_ID>
          location: <location>
          chat:
            options:
              model: gemini-2.0-flash-001
